### ISSUE TITLE
How do you call the server?

### ISSUE THREAD

**Issue by ManuelDeLeon** [chrbala/horizon-react-webpack-hmr-boilerplate#1]
In this setup, how do you do something like:

On the client:

``` js
server.isDateAvailable(date, (isAvailable) => {
  // Do something 
})
```

On the server:

``` js
function IsDateAvailable(date) {
  // Figure out if date is available
};
```

**Comment by chrbala** [comment]
That question is fairly ambiguous and not within the scope of this repo. If you're trying to retrieve data from the horizon, you can see [horizon-react](https://www.npmjs.com/package/horizon-react), or for anything else, you can see the Express docs. You'd probably want to look into something like [app.get](http://expressjs.com/en/4x/api.html#app.get.method).

**Comment by ManuelDeLeon** [comment]
There are many ways to achieve the same thing (Socket.IO for example). I just wondered how you do it, that's all.

**Comment by chrbala** [comment]
It really just depends on what you need, and without more knowledge on your specific needs it makes little sense to make a recommendation.

I've been playing around with GraphQL recently, which is some really cool tech, though it takes a bit of upfront investment to get going.
