### ISSUE TITLE
Mistake with the horizon client import in App.js

### ISSUE THREAD

**Issue by enten** [chrbala/horizon-react-webpack-hmr-boilerplate#2]
In [App.js](https://github.com/chrbala/horizon-react-webpack-hmr-boilerplate/blob/a53430a58e957b60c821e8ce99838ce3dc01079c/src/App.js#L1), there is a mistake with the horizon client import.

~~import Horizon from '@Horizon/client'~~
import Horizon from '@horizon/client'

Obviously, set the import with a lowercase H fix the "module not found" error.

**Comment by chrbala** [comment]
Ah, you're right. I'm on a Mac, so this doesn't create an error for me. I'll fix it when I get home.

**Comment by chrbala** [comment]
Fixed in 5746c88f1f06b8e5b52736a8c007e2690d6c4924!

**Comment by enten** [comment]
Thanks!
